language: generic # don't install any environment

script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "13a365a81889"
  - COMMIT_AUTHOR_EMAIL: "metodieva.daniel@gmail.com"

branches:
  only:
  - prod