language: node_js
node_js:
  - "node"

script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "13a365a81889"
  - COMMIT_AUTHOR_EMAIL: "daniela.p.metodieva@gmail.com"

branches:
  only:
  - prod